spring:
  application:
    name: webflux-coroutine-local-${random.uuid}
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99, 1.00
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include:
          - "prometheus"
          - "loggers"
          - "refresh"
---
profile: dev

spring:
  profiles: dev
  jpa.show-sql: false

